services:

  db:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}-${ENVIRONMENT}-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    container_name: ${PROJECT_NAME}-${ENVIRONMENT}-wordpress
    build: .
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "${WORDPRESS_PORT:-80}:80"
      - "${WORDPRESS_HTTPS_PORT:-443}:443"
    env_file:
      - .env
    environment:
      SERVER_NAME: ${SERVER_NAME}
      SERVER_ROOT: /app/public/
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      CADDY_SERVER_EXTRA_DIRECTIVES: |
        @wpadmin path /wp-admin
        rewrite @wpadmin /wp-admin/index.php
        @wpadminSlash path /wp-admin/
        rewrite @wpadminSlash /wp-admin/index.php
        @forbidden path /wp-config.php /.ht*
        respond @forbidden 403
        @uploadsPhp path_regexp uploads_php ^/wp-content/uploads/.*\.php$
        respond @uploadsPhp 403

    volumes:
      - wp_core:/app/public
      - ./src-configs/themes/default-theme:/app/public/wp-content/themes/default-theme
      - ./src-configs/plugins:/app/public/wp-content/plugins
      - ./src-configs/configs/wp-config.php:/app/public/wp-config.php
      - wp_uploads:/app/public/wp-content/uploads
      - caddy_data:/data
      - caddy_config:/config

volumes:
  wp_core:
  db_data:
  wp_uploads:
  caddy_data:
  caddy_config:

